name = "clipvideoai"
compatibility_date = "2024-03-17"

[site]
bucket = "./build"
entry-point = "."

[build]
command = "npm run build"
upload.format = "directory"

[env.production]
workers_dev = false
route = "clipvideoai.org/*"
zone_id = ""  # You'll need to add your Cloudflare Zone ID here 